allowBuilds:
  '@ffprobe-installer/darwin-arm64': true
  better-sqlite3: true
  electron-winstaller: true
  esbuild: true
  ffmpeg-static: true
  msw: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
