CREATE TABLE `motion_video_jobs` (
	`id` text PRIMARY KEY NOT NULL,
	`merchant_id` text NOT NULL,
	`project_id` text NOT NULL,
	`generation_usage_id` text,
	`generation_item_id` text,
	`operation_key` text NOT NULL,
	`item_key` text NOT NULL,
	`request_hash` text NOT NULL,
	`shot_id` integer NOT NULL,
	`source_asset_id` text,
	`payload_version` integer DEFAULT 1 NOT NULL,
	`payload` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`remote_task_id` text,
	`result` text,
	`output_asset_id` text,
	`output_file_path` text,
	`progress` integer,
	`poll_attempts` integer DEFAULT 0 NOT NULL,
	`max_poll_attempts` integer DEFAULT 240 NOT NULL,
	`paid_capability_used` integer DEFAULT false NOT NULL,
	`available_at` integer DEFAULT (unixepoch()) NOT NULL,
	`lease_owner` text,
	`lease_token` text,
	`lease_expires_at` integer,
	`heartbeat_at` integer,
	`error_code` text,
	`error_category` text,
	`error_message` text,
	`error_retryable` integer,
	`retry_after_seconds` integer,
	`suggested_action` text,
	`started_at` integer,
	`submitted_at` integer,
	`finished_at` integer,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`merchant_id`) REFERENCES `merchants`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`generation_usage_id`) REFERENCES `generation_usage`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`generation_item_id`) REFERENCES `generation_operation_items`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`source_asset_id`) REFERENCES `assets`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`output_asset_id`) REFERENCES `assets`(`id`) ON UPDATE no action ON DELETE set null,
	CONSTRAINT "motion_video_jobs_status_check" CHECK("motion_video_jobs"."status" IN ('pending', 'submitting', 'submitted', 'polling', 'downloading', 'saving', 'succeeded', 'failed', 'submission_uncertain')),
	CONSTRAINT "motion_video_jobs_shot_id_check" CHECK("motion_video_jobs"."shot_id" >= 0),
	CONSTRAINT "motion_video_jobs_poll_attempts_check" CHECK("motion_video_jobs"."poll_attempts" >= 0),
	CONSTRAINT "motion_video_jobs_max_poll_attempts_check" CHECK("motion_video_jobs"."max_poll_attempts" > 0),
	CONSTRAINT "motion_video_jobs_progress_check" CHECK("motion_video_jobs"."progress" IS NULL OR ("motion_video_jobs"."progress" >= 0 AND "motion_video_jobs"."progress" <= 100)),
	CONSTRAINT "motion_video_jobs_active_lease_check" CHECK("motion_video_jobs"."status" NOT IN ('submitting', 'polling', 'downloading', 'saving') OR ("motion_video_jobs"."lease_owner" IS NOT NULL AND "motion_video_jobs"."lease_token" IS NOT NULL AND "motion_video_jobs"."lease_expires_at" IS NOT NULL)),
	CONSTRAINT "motion_video_jobs_remote_task_check" CHECK("motion_video_jobs"."status" NOT IN ('submitted', 'polling', 'downloading', 'saving', 'succeeded') OR "motion_video_jobs"."remote_task_id" IS NOT NULL),
	CONSTRAINT "motion_video_jobs_succeeded_output_check" CHECK("motion_video_jobs"."status" <> 'succeeded' OR ("motion_video_jobs"."output_asset_id" IS NOT NULL AND "motion_video_jobs"."output_file_path" IS NOT NULL))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `motion_video_jobs_merchant_operation_item_unique` ON `motion_video_jobs` (`merchant_id`,`operation_key`,`item_key`);--> statement-breakpoint
CREATE UNIQUE INDEX `motion_video_jobs_generation_item_unique` ON `motion_video_jobs` (`generation_item_id`);--> statement-breakpoint
CREATE INDEX `motion_video_jobs_status_available_idx` ON `motion_video_jobs` (`status`,`available_at`,`created_at`);--> statement-breakpoint
CREATE INDEX `motion_video_jobs_status_lease_idx` ON `motion_video_jobs` (`status`,`lease_expires_at`);--> statement-breakpoint
CREATE INDEX `motion_video_jobs_merchant_project_created_idx` ON `motion_video_jobs` (`merchant_id`,`project_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `motion_video_jobs_project_shot_created_idx` ON `motion_video_jobs` (`project_id`,`shot_id`,`created_at`);
